name: quiz_programming
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.12
  http: ^0.13.4
  flutter_svg: ^1.0.1
  animate_do: ^2.1.0
  swipe: ^0.0.1
  animated_text_kit: ^4.2.1
  percent_indicator: ^4.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  image_path: "dev_assets/logo.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/topics/
    - assets/images/difficulty/
    - assets/icons/
    - assets/flares/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Gotham Pro
      fonts:
        - asset: assets/fonts/Gotham Pro Regular.ttf
    - family: Gotham Pro Bold
      fonts:
        - asset: assets/fonts/Gotham Pro Bold.ttf
